# Generated by Django 5.0.6 on 2025-01-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('patient_unique_id', models.CharField(editable=False, max_length=10)),
                ('appointment_date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pms.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pms.patientprofile')),
            ],
        ),
    ]
