# Generated by Django 5.0.6 on 2024-12-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='site_logo',
            new_name='color_logo',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='white_logo',
            field=models.ImageField(default=0, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
