# Generated by Django 5.0.6 on 2025-01-24 17:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_onlineappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineappointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineappointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onlineappointment',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='onlineappointment',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid Bangladesh phone number (e.g., 01712345678).', regex='^01[3-9]\\d{8}$')]),
        ),
    ]
