# Generated by Django 5.0.6 on 2024-12-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
