# Generated by Django 5.0.6 on 2025-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
