# Generated by Django 5.0.6 on 2025-02-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='opening_hours',
            field=models.CharField(default='Saturday - Thursday: 6.00 am - 10.00 pm, Friday Closed', max_length=255),
        ),
    ]
