# Generated by Django 5.0.6 on 2024-12-26 15:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_department_alter_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='doctor_profile_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid Bangladesh phone number (e.g., 01712345678).', regex='^01[3-9]\\d{8}$')]),
            preserve_default=False,
        ),
    ]
