# Generated by Django 5.0.6 on 2025-02-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineAppointment',
        ),
    ]
