# Generated by Django 5.0.6 on 2025-02-07 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_delete_onlineappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOnlineAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_full_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a valid Bangladesh phone number (e.g., 01712345678).', regex='^01[3-9]\\d{8}$')])),
                ('patient_email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pms.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_online_appointments', to='pms.doctorprofile')),
            ],
        ),
    ]
