# Generated by Django 5.0.6 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_publiconlineappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiconlineappointment',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
