# Generated by Django 5.0.6 on 2025-02-14 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_publiconlineappointment_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiconlineappointment',
            name='age',
        ),
        migrations.AddField(
            model_name='publiconlineappointment',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
