# Generated by Django 5.0.6 on 2025-01-02 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeProfile',
        ),
    ]
